version: '3.8'

services:
  hotel-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hotel-booking-app:latest
    container_name: hotel-booking-app
    ports:
      - "8090:8090"
    environment:
      - DB_URL=jdbc:oracle:thin:@//host.docker.internal:1521/xepdb1
      - DB_USERNAME=ivan
      - DB_PASSWORD=1234
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//host.docker.internal:1521/xepdb1
      - SPRING_DATASOURCE_USERNAME=ivan
      - SPRING_DATASOURCE_PASSWORD=1234
      - SERVER_PORT=8090
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=zerokinger@gmail.com
      - MAIL_PASSWORD=vqgyznauddovegbs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
