apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel-booking-config
  labels:
    app: hotel-booking
data:
  SPRING_DATASOURCE_URL: "jdbc:oracle:thin:@//oracle-service:1521/FREEPDB1"
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  FILE_UPLOAD_DIR: "/data/uploads"
---
apiVersion: v1
kind: Secret
metadata:
  name: hotel-booking-secret
  labels:
    app: hotel-booking
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "ivan"
  SPRING_DATASOURCE_PASSWORD: "1234"
  JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  SPRING_MAIL_USERNAME: "service@hotelbooking.com"
  SPRING_MAIL_PASSWORD: "app-specific-password"
