apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-deployment
  labels:
    app: oracle-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      containers:
        - name: oracle-free
          image: gvenzl/oracle-free:latest
          ports:
            - containerPort: 1521
          env:
            - name: ORACLE_PASSWORD
              value: "1234"
            - name: APP_USER
              value: "ivan"
            - name: APP_PASSWORD
              value: "1234"
            - name: ORACLE_DATABASE
              value: "FREEPDB1"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-service
  labels:
    app: oracle-db
spec:
  ports:
    - port: 1521
      targetPort: 1521
  selector:
    app: oracle-db
